

UDP_SERVER_HOST:        192.168.1.76
UDP_SERVER_PORT:        6000
HTTP_SERVER_PORT:       5000
MAX_BYTES:              2046

SHARED_KEY_FRAME_DIR:   'Z:/key_frame/'
SHARED_SCREEN_SHOT_DIR: 'Z:/screenshot/'
SHARED_VIDEO_DIR:       'Z:/videos/'

FPS_LOCK:               25

CONF_THRESHOLD:         0.4
